# Generated by Django 2.1.7 on 2019-04-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_registermodel_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
